version: '2'
services:
    easycount-app:
        image: easycount
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://easycount-postgresql:5432/easycount
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    easycount-postgresql:
        extends:
            file: postgresql.yml
            service: easycount-postgresql
